In [38]:
import numpy as np
import pandas as pd

In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,3,4])

np.dot(arr1,arr2)

np.int64(20)

ECM

$$ECM = \frac{1}{n}\sum(y - \hat{y}) ^2$$

In [41]:
y = np.array([1,2,3])
y_hat = np.array([2,4,6])

print(y - y_hat)
print(((y - y_hat) ** 2).sum())

def ecm(y,y_hat):
    """Funcion para calcular el errore cuadratico medio de dos vectores
    
    Se asume que y y y_hat tienen el mismo tamaño
    
    """
    if len(y) != len(y_hat):
        print("Los vectores tienen que tener el mismo tamaño")
    
    if not isinstance(y, np.ndarray) or not isinstance(y_hat, np.ndarray):
        y = np.array(y)
        y_hat = np.array(y_hat)
    
    diferencia_cuadrado = (y - y_hat)**2
    suma = diferencia_cuadrado.sum()
    return suma / len(y)

    return ((y - y_hat) ** 2).sum() / len(y)

ecm([2,4,6],[1,2,3])

[-1 -2 -3]
14


np.float64(4.666666666666667)

In [46]:
x = np.array([1,2,3])
y = np.array([2,4,6])

(x * y).sum()

np.int64(28)

In [48]:
def pendiente(b: float, x: np.ndarray, y: np.ndarray) -> float:
    return (((x * y).sum()) - b * x.sum()) / (x ** 2).sum()

pendiente(5,x,y)

np.float64(-0.14285714285714285)

In [ ]:
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]])

b = np.array([8,-11,-3])

x = np.linalg.solve(A,b)
print(x)

[ 2.  3. -1.]


In [52]:
A

array([[ 2,  1, -1],
       [-3, -1,  2],
       [-2,  1,  2]])

In [51]:
A.T

array([[ 2, -3, -2],
       [ 1, -1,  1],
       [-1,  2,  2]])